// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylekdrzjfqwtarskejnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZWtkcnpqZnF3dGFyc2tlam56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjk3NTgsImV4cCI6MjA2MjgwNTc1OH0.LSufo_a5PTAEldL0CBRLC9zLjCfjuDmWyR4iyjO1Sk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);